### ISSUE TITLE
JARM Matches

### ISSUE THREAD

**Issue by terminatordoink** [360quake/CobaltStrike-JARM#2]
What if few of our servers have similar JARM signatures listed in the CSV file, is it a 100% certainty that our external facing infrastructure is compromised?

**Comment by imjdl** [comment]
Sorry to reply only now. It can't be 100 percent certain. We believe that JARM is only an auxiliary tool and not a direct evidence to determine the victim host. Please refer to: 
https://quake.360.cn/quake/#/reportDetail?id=5fd8336e61cd410c7f25b898
https://blog.cobaltstrike.com/2020/12/08/a-red-teamer-plays-with-jarm/

**Comment by terminatordoink** [comment]
Thanks imjdl for responding, and thanks to you and your team for the guide
